### ISSUE TITLE
does not work in chrome

### ISSUE THREAD

**Issue by camerondavison** [yamafaktory/rust-wasm-webpack#6]
I see this
```
Uncaught (in promise) RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.
    at Object.30 (0.bundle.js:1)
    at t (bundle.js:1)
```
I am running chrome `Version 65.0.3325.181 (Official Build) (64-bit)`

**Comment by camerondavison** [comment]
note https://github.com/webpack/webpack/issues/6475

**Comment by yamafaktory** [comment]
@a86c6f7964 Hi & thanks for auto-responding on that topic! Sadly for now Chrome is still limited. There's a really nice explanation here too https://github.com/rustwasm/wasm-bindgen/blob/master/examples/hello_world/README.md#caveat-for-chrome-users.
